phoenix_container:
  build: .
  volumes:
    - .:/usr/src/app/
  ports:
    - "7000:7000"
  links:
    - database

database:
  image: postgres:latest
  environment:
    POSTGRES_PASSWORD: dbuser
    POSTGRES_USER: dbuser
  ports:
    - "5432:5432"
  volumes:
    - ./data:/data
